[build]
builder = "nixpacks"

[deploy]
startCommand = "waitress-serve --host=0.0.0.0 --port=$PORT --call app:create_app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[build.env]
PYTHON_VERSION = "3.11.9"